name: Update EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'


  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Build Docker Image
        id: build_docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: backend/
          push: true
          tags: |
            marcotfm/zoologico-hackaton:v1
            marcotfm/zoologico-hackaton:latest

  deploy:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Checkout code from main branch
        uses: actions/checkout@v2   

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get Auto Scaling Group ID
        id: get_asg_id
        run: |
          stack_name="infraestructure"
          stack_id=$(aws cloudformation describe-stacks --stack-name $stack_name --query 'Stacks[0].StackId' --output text)
          asg_name=$(aws cloudformation describe-stack-resources --stack-name $stack_id --logical-resource-id MyASG --query 'StackResources[0].PhysicalResourceId' --output text)
          echo "::set-output name=asg_id::$asg_name"

      - name: Start Instance Refresh
        run: |
          asg_id=${{ steps.get_asg_id.outputs.asg_id }}
          aws autoscaling start-instance-refresh --auto-scaling-group-name $asg_id --preferences '{"MinHealthyPercentage": 50, "InstanceWarmup": 200}'
