name: Build
on:
  pull_request:
    types:
      - closed
    branches: [ main ]

permissions:
  pull-requests: write
  contents: write
  actions: read

jobs:
  run-tests:
    name: Run tests
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
      - name: Run tests with pytest
        run: |
          pip install pytest pytest-cov
          pytest backend/tests --cov --cov-report xml:backend/tests/report/coverage.xml
      - name: Generate Code Coverage Report
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: backend/tests/report/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}

  post-code-coverage-comment:
    name: Post Code Coverage Comment in PR
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Post Code Coverage Comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}